### ISSUE TITLE
Option to edit the logo and intro text

### ISSUE THREAD

**Issue by sathpra** [hmislk/hmis#1152]
We want to customize the logo and the intro text. It would be better to have that feature.

**Comment by buddhika75** [comment]
@sathpra Need to go to admin > Manage Institutions > Preferences > Application Preferences > 

Change Logo URL, Login Header and Login Text.

**Comment by sathpra** [comment]
@buddhika75 I tried to edit the logo and the login text. But the options aren't there. I updated the master branch to the current one before trying.

**Comment by buddhika75** [comment]
Need to go to admin > Manage Institutions > Preferences > Application Preferences >

Change Logo URL, Login Header and Login Text.

If not please call me.
