### ISSUE TITLE
External Workload Report UI implementing for lab report

### ISSUE THREAD

**Issue by Senula88** [hmislk/hmis#1377]
Fiter by Date Range (From Date & to Date)			
Filter by Branch / Institution			
Filter by Laboratory (Biochemestry, Pathelogy, ......)			
VisitType - All / OP / IP / CC			
Filter by CC Name			
Filter by CC Route			
Filter by patient MRN			
Filter by Investigation			
Refering Doctor Name

**Comment by DamithDeshan** [comment]
This Issue Already Fixed
