### ISSUE TITLE
Daily Payment

### ISSUE THREAD

**Issue by piumini** [hmislk/hmis#223]
Daily Payment = Monthly Salary / Month days - (off days + ph + poya) 
Daily Payment is not affected by number of days worked or worked on poya or ph. 
Daily payment varies from month to month as the days of month and ph/poya varies.

Salary = Daily Payment \* working days
Salary varies from month to month because of working days changes and daily payment varies.

**Comment by piumini** [comment]
ONLY paid through petty cash.
NO banking.
Same Salary cycles as Permanent.

**Comment by piumini** [comment]
Same Roster.
Same Over 45 (Usually no because of increased value for 45)
Additional Payments (Hourly) same
Rate = Monthly Salary / 200
Rate does not vary for ph/poya
No PH/Day Off/
Leaves only for 1/2 per month
Late NO pay - Yes
Early Out - Yes
No Pay Rate = Daily Rate

**Comment by piumini** [comment]
Salary Advance +
Loans -
Festival -

**Comment by piumini** [comment]
Two Different Salary Cycles for Permanent and Temporary

**Comment by buddhika75** [comment]
Already there. Closing the issue.
