### ISSUE TITLE
Channelling Reports - Doctor Counts

### ISSUE THREAD

**Issue by piumini** [hmislk/hmis#249]
report is needed for all the data wich is enterd.

**Comment by buddhika75** [comment]
What all data? I can not understand.

**Comment by lahirumadushanka** [comment]
already exist please check.

**Comment by lahirumadushanka** [comment]
not available pharmacy items and store items.dilshan attending to those.

**Comment by buddhika75** [comment]
Changed to Channelling Reports - Doctor Counts
