### ISSUE TITLE
pharmacy / summery

### ISSUE THREAD

**Issue by piumini** [hmislk/hmis#267]
![scan0017](https://cloud.githubusercontent.com/assets/7201585/8205292/ff66e9ca-150c-11e5-987c-70ec072b6d0d.png)

![bill](https://cloud.githubusercontent.com/assets/7201585/8205320/5cfefc12-150d-11e5-833a-8664ed10333e.png)

**Comment by lahirumadushanka** [comment]
there is no issue..when we creating a bill we create two numbers one is Dep_ID, the other one is Ins_ID. you can see that also in the picture. when cancelling a bill same process. in the summery it only displays Dep_ID. please close this. this is not an issue.

**Comment by buddhika75** [comment]
Already there. Closing the issue.
