### ISSUE TITLE
OPD Token Number Generation

### ISSUE THREAD

**Issue by buddhika75** [hmislk/hmis#3050]
OPD Token Number Generation Need the following 
1. Bills by Department
2. Bills by Department and Category
3. Bills by Department, Category and fromStaff

**Comment by buddhika75** [comment]
Multiple Bills will be generated for a single order for investigation or service depending on the following characteristics

Single Bill for All Orders
One Bill for each Department that provides the Service or Investigation
One Bill for each Department and service/investigation  category

**Comment by Senula88** [comment]
Already Done
