### ISSUE TITLE
doctor payment report error (221 & dpay system)

### ISSUE THREAD

**Issue by piumini** [hmislk/hmis#306]
doctor payment report error.

(DPAY)
inward doctor payment due report in (dpay) system  
(income by category report net total - book keeping summery Collection for the day total = doctor payment day)

(221)
OPD doctor payment due report in 221

**Comment by HNDITDushan** [comment]
221 opd due is corected plz check daily return (by month) and due again

**Comment by piumini** [comment]
dpay???????????????????????
