### ISSUE TITLE
Channelling Report - Annual Counts by Month

### ISSUE THREAD

**Issue by buddhika75** [hmislk/hmis#337]
![ann](https://cloud.githubusercontent.com/assets/1226946/10335030/08131466-6d0c-11e5-9543-3049a0e7fd62.jpg)

**Comment by HNDITDushan** [comment]
done
![aaaaa](https://cloud.githubusercontent.com/assets/3907163/10559331/18bbfc76-750c-11e5-92a2-55106432dc42.JPG)
