### ISSUE TITLE
Create a Lab Administration page same as lab summeries page

### ISSUE THREAD

**Issue by isurupathum1996** [hmislk/hmis#358]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by buddhika75** [comment]
You need to give a description on the issue like following.

**The problem**
When Lab Administration Page is viewed, the buttons are not properly arranged.

**The solution suggested**
 In contrast, the buttons are properly arranged in the Lab Summaries Page. Need to arrange buttons in Lab Administration page in the same style as Lab Summaries Page.

Alternatives you've considered
All pages need to have the same look and feel. So make them all look similar. No other solution I can think of.

Additional context
Attach screen shots

**Comment by Gayan830** [comment]
completed.
