### ISSUE TITLE
OPD/Pay Doctor/Staff

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#3683]
Pay/OPD/Pay Doctor/Staff
Staff Payments/Payment Method- After selecting one payment method all method was displayed.
Staff Payments/Excel Button- After clicks error page was displayed.
Staff Payments/Payment Method- The word 'Payment Methord'was wrong. (Payment Method)
Staff Payments/Charge- Total fee was displayed.(Hos fee + Dr Fee)
Payment Details/Pay/PAYMENT VOUCHER/Phone - Not retrieve the Phone 
Payment Details/Pay/PAYMENT VOUCHER/Fax - Not retrieve the Fax
Payment Details/Pay/PAYMENT VOUCHER/Email- Not retrieve the Email
Payment Details/Pay/PAYMENT VOUCHER/Payment Type- If have a different payment method it was displayed as cash.
Payment Details/Pay/PAYMENT VOUCHER/New Payment Button- Need space between button and ribbon
Payment Details/Pay/PAYMENT VOUCHER/New Payment Button- After click the button 'Please select a Staff Memeber'was displayed.
Payment Details/Pay/PAYMENT VOUCHER/Print Button- Need space between button and ribbon

(payment_staff_bill.xhtml)

**Comment by DamithDeshan** [comment]
some one are already fixed.
