### ISSUE TITLE
Pay/Receive/Credit Company/OPD/Due Search

### ISSUE THREAD

**Issue by DeshaniPubudu** [hmislk/hmis#3685]
credit/credit_company_opd_due.xhtml
Pay/Receive/Credit Company/OPD/Due Search/OPD Dues and Access/OPD Credit Due

Due Search/OPD CREDIT
1. Paid Amount - Not retrieve the Paid Amount 
Due Age 
1. Process Due Age Button - After clicks error page was displayed.  
2. Process Due Age Button - The button wasn't aligned.    

credit/credit_company_opd_due.xhtml
Pay/Receive/Credit Company/OPD/Due Search/OPD Dues and Access/OPD Credit Excess

Excess Search/EXCESS SEARCH
1. Billed Amount - The amount wasn't aligned.
2. Paid Amount - The amount wasn't aligned.
3. Net Amount - The amount wasn't aligned.

Excess Age
1. Process Access Age Button - After clicks error page was displayed.  
2. Process Access Age Button - The button wasn't aligned.
3. Process Access Age Button - The word 'Access' should be 'Excess'

**Comment by DamithDeshan** [comment]
This Section Change  and Updated
