### ISSUE TITLE
Search Inpatient Direct Issues by Bill

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#3797]
Pharmacy/Inpatient Medication Management/Search Inpatient Direct Issues by Bill/View Bill- The item request department wasn't updated
(Item add department was displayed)

Cancellation/Dealer Name- The word "Dealor" is correct as "Dealer"
Cancellation/Dealer Name-Not retrieves the Dealer Name
If have more than one drug- If return one item and cancel other items it wasn't allowed to cancel because the returned item was there.
If have more than one drug- If the user wants to cancel one item added the whole item was canceled.

**Comment by DamithDeshan** [comment]
This Issue is already Fixed
