### ISSUE TITLE
Pharmacy Purchase Orders Approval

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#4018]
Procurement/Purchase Orders Approval/Purchase Orders To Approve
(pharmacy/pharmacy_purhcase_order_list_to_approve.xhtml)

View/Cancel- The already returned item can be canceled again. (After approved come up data was missing ex: Approved Person,
PO Number & etc..)

**Comment by DeshaniPubudu** [comment]
The issue was fixed
