### ISSUE TITLE
Search Only Registerd Patietns as a preference

### ISSUE THREAD

**Issue by buddhika75** [hmislk/hmis#408]
Under OPD Billing, we have to search patients, butt need to click search only registered patients every time. Need to take it out as a preference.

**Comment by mkyenze** [comment]
hi, did you get the whole databases tables, because mine is generating less tables

**Comment by buddhika75** [comment]
Please use the branch Arogya2021.

To sort out any issues, please schedule a google meet, any day feasible to
you (Except between 6am 9am ISP and 5pm to 10pm ISP)

Regards

**Comment by buddhika75** [comment]
currently available
