### ISSUE TITLE
Extend Features by Modules

### ISSUE THREAD

**Issue by SUNILASOFTWARE** [hmislk/hmis#409]
Some of the required features are missing in the main system. For Example, a system to manage a dental clinic.

Can you develop a methodology so that plugins or modules can be developed adhering to certain specifications so that new functionalities can be added.

**Comment by buddhika75** [comment]
We are working on the possibility to add modularity.

**Comment by niluka** [comment]
We are planning to convert this monolithic design in to a set of microservices incrementally. The necessity to have pluggable modules is lost in that scenario.
