### ISSUE TITLE
need sample database data

### ISSUE THREAD

**Issue by hewrie** [hmislk/hmis#414]
Details:
i have running hmis from idea. but there are no data on hmis. please give sql data for trying hmis. and give username and password for login. thank you

**Comment by buddhika75** [comment]
We will include a sample sql in the project folder itself.

**Comment by hewrie** [comment]
Oke thank you.. I'll waiting for.

**Comment by ayushi84** [comment]
can u please share the sql file of this project. i am not able too search that file in folder

**Comment by buddhika75** [comment]
A blank database is automatically creased by EcliseLink.

**Comment by ayushi84** [comment]
Thanks for replying. But it is not created may be. Can u send me SQL file
of blank dtabase. Please it is very helpful for me.

**Comment by ayushi84** [comment]
i found the folder of sql file but create table command file is not there. Please help me. its urgent
![Untitled](https://user-images.githubusercontent.com/34335187/94848693-fda89000-0441-11eb-9fd1-ce9857790e94.png)

**Comment by buddhika75** [comment]
Are you working with Netbeans? If so, please create a database (MySQL for example) and create a connection string. The open the persistance.xml file. Create a new data source using the connection. Then select create-tables as an option. Then it will create a database for you.

https://www.eclipse.org/eclipselink/documentation/2.5/jpa/extensions/p_ddl_generation.htm

**Comment by simendipeter** [comment]
wanted to try out this application. i am kindly requesting demo data

**Comment by azharshaikh7866** [comment]
I have created db in mysql....below is my persistence.xml:
`<?xml version="1.0" encoding="UTF-8"?>
<persistence version="2.0"
	xmlns="http://java.sun.com/xml/ns/persistence"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd">
	<persistence-unit name="hmisPU" transaction-type="JTA">
		<jta-data-source>java:app/dsArogys</jta-data-source>
		<exclude-unlisted-classes>false</exclude-unlisted-classes>
		<shared-cache-mode>ALL</shared-cache-mode>
		<properties>
			
			<property name="javax.persistence.jdbc.driver"
				value="com.mysql.jdbc.Driver" />
			<property name="javax.persistence.jdbc.url"
				value="jdbc:mysql://localhost:3306/hmis" />
			<property name="javax.persistence.jdbc.user" value="root" />
			<property name="javax.persistence.jdbc.password"
				value="" />
		</properties>
	</persistence-unit>
</persistence>`

I have noticed there are 2 persistence.xml files in the project, which 1 should I change?

**Comment by azharshaikh7866** [comment]
There should be atleast a sql script for admin user. Post-installation there is nothing much that can be added as it gives "You are NOT authorized" message everywhere.
Please help me to add a user.

**Comment by buddhika75** [comment]
Sorry for the delay. I will add a startup script that will create the database on the first run. Until that, I will give a blank database. Please give me two days,

**Comment by aartigrover84** [comment]
> There should be atleast a sql script for admin user. Post-installation there is nothing much that can be added as it gives "You are NOT authorized" message everywhere.
> Please help me to add a user.

I am also facing the same issue. do you have a sample dataset that can be added first time and then we can explore the app? or atleast a way to add an admin user?

**Comment by buddhika75** [comment]
Sorry for the delay to reply. Please find it in the next commit.

**Comment by mkyenze** [comment]
Hi, after running the system successfully, it gives "You are NOT authorized" message everywhere.
Please help me to add a user.

**Comment by buddhika75** [comment]
Need to add privileges.

**Comment by mkyenze** [comment]
Thanks solved. what about this, This user has no privilage to login to any Department. Please conact system administrator.

**Comment by mkyenze** [comment]
thank you so much, i will contact you if anything else of difficult arises

**Comment by mkyenze** [comment]
Hi, how can i do away with this page and start feeding in info into db

Very Dangerous Section.
Please do not touch this page without the written permission from the lead
software developer.

**Comment by mkyenze** [comment]
Hi, how can i be able to fill information here 

Very Dangerous Section.
Please do not touch this page without the written permission from the lead software developer.

**Comment by Ippezrobert** [comment]
I have been looking forward to trying this application but couldn't get it running. if someone can provide a video tutorial for setting up dev environment to run the application it will help many new comers like me

**Comment by buddhika75** [comment]
Details are in the wiki
https://github.com/hmislk/hmis/wiki

Blank Database is created when run for the first time. Data Needed to be added to the system using the UI.
