### ISSUE TITLE
How to create the database schema (tables) in MySQL?

### ISSUE THREAD

**Issue by rejeevd** [hmislk/hmis#420]
Details:
I am trying to install HMIS in my local machine. I have installed MySQL and Glassfish and deployed the war. However, the application is not running as the database schema is missing. How can I create the database schema?
Is there any create tables SQL script available?

**Comment by rejeevd** [comment]
I figured it out.
We need to uncomment following in the persistence.xml
```
<properties>
      <property name="javax.persistence.schema-generation.database.action" value="create-or-extend-tables"/>
    </properties>
```
This will automatically create the tables on the first access.

**Comment by buddhika75** [comment]
This code in persistence.xml will create tables for you on first run.

    <properties>
      <property name="javax.persistence.schema-generation.database.action" value="create-tables"/>
    </properties>

This will create or add new fields to the existing tables
    <properties>
      <property name="javax.persistence.schema-generation.database.action" value="create-or-extend-tables"/>
    </properties>

If we remove that, there will be no creation of tables.
