### ISSUE TITLE
Sample Data to run the project

### ISSUE THREAD

**Issue by ansuman-logicoy** [hmislk/hmis#425]
Details: Need sample data to run the project. Though the schema is getting created but without sample data the application is not going run.

Please provide database dump. Appreciate the great work you have done.

**Comment by mkyenze** [comment]
hey, after generating db, some tables like patient table is still missing, might you have full db tables to share kindly

**Comment by Ippezrobert** [comment]
@buddhika75 is there any demo database and first time readme for to bring the system to run... I have never got the system running yet am curious to see what it can offer as the modules in the README.md file interest a lot. Kindly assist me in setting up the system and a sample demo database for testing... 
Thanks and regards
