### ISSUE TITLE
Cannot search admission by giving the dates

### ISSUE THREAD

**Issue by PasinduW99** [hmislk/hmis#4306]
Cannot search admission by giving the dates
When I give the From Date and To Date and search for admissions, it gives an error. This was seen only at Sethma. But it worked finely during the past days.
javax.servlet.ServletException: javax.ejb.EJBException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.11.payara-p1): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: The value '31:48:54' is an invalid TIME value. JDBC Time objects represent a wall-clock time and not a duration as MySQL treats them. If you are treating this type as a duration, consider retrieving this value as a string and dealing with it according to your requirements.
Error Code: 0

**Comment by buddhika75** [comment]
This was due to the error of the field WORKTIME_ID was given the data type Time. COrrected in the database. Not an issue with the code/
