### ISSUE TITLE
To add an extra  column in the bill indicating the date of the report collection.

### ISSUE THREAD

**Issue by thanukaru** [hmislk/hmis#447]
As the laboratories have fixed time period for reporting, specific for each investigations.
Is it possible to add an extra column in the bill(parallel to the item and value) indicating the date of report collection.

**Comment by DamithDeshan** [comment]
This Option has bean Already in system.
> Search Lab Report
> Hovering the Order Number 
> Now you See following details in each Investigation
> - Bill No
> - Billed from
> - Sampled (Date - Time)
> - Received (Date - Time)
