### ISSUE TITLE
Unable to login with new user

### ISSUE THREAD

**Issue by ghost** [hmislk/hmis#457]
Running this first time and having some challenges, scattered views as the login screen shows while adding a new user. After adding a new user, institution, and department, I am still unable to login into the system.

<img width="959" alt="Screenshot 2022-12-02 at 13 36 34" src="https://user-images.githubusercontent.com/11539579/205300510-4940e02c-dd32-43f8-9cf9-275f312b8003.png">
<img width="1036" alt="Screenshot 2022-12-02 at 13 36 44" src="https://user-images.githubusercontent.com/11539579/205300523-62083f5a-25ca-4d61-ad49-403f50c010a4.png">
<img width="1483" alt="Screenshot 2022-12-02 at 14 01 27" src="https://user-images.githubusercontent.com/11539579/205300532-47343306-c63c-4d55-9e44-fcc0716f53ba.png">

Is there any sample data?

**Comment by buddhika75** [comment]
Do not create a User First

On the first login, you will have the access to some admin functions. 

1. Create an Institution
2. Create a Department (after clicking the add button), Select the previously created institution as the institution
3. Create a user
4. Add Privileges to the user
5. Add Loggable departments to the user
6. Then create another user
7. Once you save the second user, the application reverts to normal mode. You can use first create the username and password

We are working to improve the initial login soon so that there will be no such trouble.

**Comment by mnomansadiq** [comment]
Let me follow these instructions.

**Comment by mnomansadiq** [comment]
There is a problem in adding up a new institution, after filling out the form when I click on add button, no error shows on the UI and on the console and there is no institution appearing on the left-hand side. I try to search the records in the INSTITUTION table and its empty. 

I am checking the error on the glassfish-> domain->server.log file, is there any logging at the application level as well?

**Comment by buddhika75** [comment]
Please click the add button before starting to add

**Comment by mnomansadiq** [comment]
no luck with that. first click on add button, fill the form and then click on add again but nothing added into the table.

**Comment by mnomansadiq** [comment]
after adding the institution, it successfully shows on the left side but when I moved to the department, same first clicked on add button and then fill the forms, but no institution was showing there(assuming a dropdown list) even try to type the institution but it removes and nothing adding when click on save button. Any tip?

**Comment by buddhika75** [comment]
It is an autocomplete. Try typing 3 letters of the institution name and wait. If still difficult, please schedule a zoom meeting for 15 minutes and invite me to sort that out. buddhika.ari@gmail.com

**Comment by mnomansadiq** [comment]
Auto complete seems to be not working. 
Thanks yes it would be very helpful if you guide on this. I will send you an invite on Sunday.

**Comment by buddhika75** [comment]
Already Added
