### ISSUE TITLE
Fixing Edit Row Item Qty in All Transfer Stock -> Goods Receipt

### ISSUE THREAD

**Issue by DamithDeshan** [hmislk/hmis#4594]
Fixing Edit Item Qty in All Transfer Stock -> Goods Receipt
> Improving UI
> Fix Row Option
> Add BillTypeAtomic for Bill

**Comment by DamithDeshan** [comment]
@buddhika75 
Issuing Qty is wrong. 
because Issuing Qty = qty + freeqty*2
pharmacy -> procurement -> Goods Receipt -> View GRN -> Transfer All Stocks (pharmacy_transfer_issue.xhtml)

**Comment by buddhika75** [comment]
I can not replicate the error now. Please recheck. I will close this issue, if persists please reopen it.
