### ISSUE TITLE
SMS not working in Lab Report

### ISSUE THREAD

**Issue by DeshaniPubudu** [hmislk/hmis#4630]
SMS not working in Lab Report

lab/patient_report.xhtml
Lab/Reporting/Action/New Lab Report

**Comment by buddhika75** [comment]
SMS are going for Lab Reports.

May be wrong SMS credentials.

Can you double check and reopen if still persists.

Check Other instances as well.

@DeshaniPubudu 
I will close this. You may open if persists.
