### ISSUE TITLE
The two token circles displayed on the print

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#4650]
Channel/Channel Booking/Manage Booking/Reprint
The two token circles displayed on the print

(faces/channel/manage_booking.xhtml)

**Comment by DARKDRAGON-LK** [comment]
Fixed in [version  3.0.0.20240419.7](https://github.com/hmislk/hmis/commit/67d83e48422ff2ed9ddab3fb5056baed26d94c0c)

**Comment by DARKDRAGON-LK** [comment]
Fixed in [version  3.0.0.20240419.7](https://github.com/hmislk/hmis/commit/67d83e48422ff2ed9ddab3fb5056baed26d94c0c)
