### ISSUE TITLE
After Refunding a bill, its "Manage Booking" page was not loaded.

### ISSUE THREAD

**Issue by DeshaniPubudu** [hmislk/hmis#4657]
Refund button - Validation message is not displayed after clicking the refund button with a comment
Refund button - Click after the button, Blank page was loaded

Manage Booking/Refund
channel/manage_booking.xhtml

On the channel booking page, select Refund Bill and click "Manage Booking", then you will be redirected to a blank page.
channel/channel_booking.xhtml

**Comment by DARKDRAGON-LK** [comment]
This was a error on Demo not in the system.
