### ISSUE TITLE
Channel Payment Receipt

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#4659]
Channel/Channel Booking/Manage Booking/Settle/Settle Credit Booking/Booked

Choose Payment Method-After settling the bill Channel Payment Receipt was not displayed fully
Settle/Channel Payment Receipt/Cash/Paper Type- After changing the paper type it goes back to manage booking.
(channel/manage_booking.xhtml)

**Comment by Irani96** [comment]
issue fix

**Comment by DARKDRAGON-LK** [comment]
No Issue Found
