### ISSUE TITLE
Channel Search

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#4682]
Search/Search Button- Need space between the button and the search text box.
Search/Search Button- The button color & icon were missing.
Search/Search Button- Sometimes data wasn't displayed.
Search/Booking Id- The word 'Id' should be 'ID'
Search/Booking Id- Not retrieve the ID
Search/Speciality- The word 'Sepeciality' was wrong
Link- After clicking on the link error page was displayed.

(channel/manage_booking.xhtml)

**Comment by DARKDRAGON-LK** [comment]
This was removed form the system
