### ISSUE TITLE
Before adding the paid bill after changing the time and canceling minus value was displayed on the Gross Total

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#4826]
Before adding the paid bill after changing the time and canceling minus value was displayed on the Gross Total
(if added 1.00 pm Rs 2600 bill and change the time on All Financial Transaction Summary to past time 1.15 pm and that time cancel the bill then displayed -2600)
After that came up all calculations were wrong.

**Comment by DARKDRAGON-LK** [comment]
This is a not a Issue. This is the System Default Behavior.
