### ISSUE TITLE
Hello, could you please tell me the database name, user, and password for connecting to mysql-connector-java-8.0.18.jar?

### ISSUE THREAD

**Issue by ms2546088** [hmislk/hmis#4906]
![2024-04-29 16 40 26](https://github.com/hmislk/hmis/assets/106522529/11724557-3411-4bda-92eb-e3a0a57528e4)
Expert Question 1:Hello, could you please tell me the database name, user, and password for connecting to mysql-connector-java-8.0.18.jar? Or for mysql-connector-java-8.0.30.jar?
Expert Question 2:How can the following error be fixed? On executing 
C:\glassfish\bin>asadmin deploy C:\hmis\target\sethma-3.0.0.war
remote failure: Error occurred during deployment: Exception while loading the app : java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Unable to add listener of type: org.primefaces.webapp.UploadedFileCleanerListener, because it does not implement any of the required ServletContextListener, ServletContextAttributeListener, ServletRequestListener, ServletRequestAttributeListener, HttpSessionListener, or HttpSessionAttributeListener interfaces. Please see server.log for more details.
Command deploy failed.

**Comment by buddhika75** [comment]
To connect your application to a MySQL database using MySQL Connector/J, please follow these steps:

Create a Connection Pool: Configure a connection pool in your Payara/GlassFish server. Verify that the connection pool can successfully connect to your database ("ping" the database to confirm).

Create a JDBC Resource: Establish a JDBC resource in Payara/GlassFish, such as jdbc/hims, and link it to the correct connection pool you have set up.

Configure persistence.xml: In your persistence.xml file, reference the JDBC resource name that you created:

`<jta-data-source>jdbc/hims</jta-data-source>
`
Please ensure each issue or question is raised separately for clarity and detailed attention.

**Comment by ms2546088** [comment]
Thank you very much for your guidance
