### ISSUE TITLE
Collecting Centre Bill was not added to the Shift End Funds

### ISSUE THREAD

**Issue by DeshaniPubudu** [hmislk/hmis#4994]
Collecting Centre Bill was not added to the Shift End Funds "In"
But, Collecting centre cancel bill amount was displayed in "Out" 

Payment/Financial Transaction Manager/Shift End Funds
cashier/shift_end_summery_bill.xhtml

**Comment by buddhika75** [comment]
Collecting centre bill are taken without any money
Money is paid separately under the payments
