### ISSUE TITLE
Some of the payment methods were missing on Sale and Sale for Cashier

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#5171]
Some of the payment methods were missing on Sale and Sale for Cashier
(/pharmacy/pharmacy_bill_retail_sale.xhtml)
(pharmacy/pharmacy_bill_retail_sale_for_cashier.xhtml)

**Comment by buddhika75** [comment]
Now it has to be configured from the Options. It was intentional. Not an issue.
