### ISSUE TITLE
Cancel channel wasn't updated

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#5573]
The cancel channel wasn't updated
channel/channel_booking_by_date.xhtml

**Comment by DARKDRAGON-LK** [comment]
No Issue found In this. C is for complete
`<span class="text-center mx-1" > 
              <h:outputText style="font-weight: bolder" value="C"/><br/>
              <p:badge value="#{s.completedPatientCount != null ? s.completedPatientCount : ' '}" severity="danger" size="large" styleClass="mr-2"></p:badge>
   </span>`
