### ISSUE TITLE
Adding new Items do not bring them to OPD Billing

### ISSUE THREAD

**Issue by buddhika75** [hmislk/hmis#5580]
**Describe the bug**
Go to Admin menu > Manage Items > OPD Service
Add New Service

Go to Admin Menu > Manage Prices > Add price for above Item

Then GO TO OPD Billing
Click Refresh button to load new item

CHeck weather new items appears there, It does not appear as per Dr Anura

Please check and comment here

**Comment by Irani96** [comment]
After refresh added item was not displayed
