### ISSUE TITLE
External Doctor for Collection Center Billing

### ISSUE THREAD

**Issue by DeshaniPubudu** [hmislk/hmis#6674]
External Doctor for Collection Center Billing 

(With Only add doctors if they have submitted all the details of doctor with SLMC. For CC Bills they need to feed Referring Doctor Name is not Available in the system they need to feed that doctor name in the CC Invoice. That Doctor name no need to save in our consultant list.)

**Comment by DamithDeshan** [comment]
### **Worning !**
This External Doctor use **Only Bill**.
So this Dorctor name can't use to any Reports
