### ISSUE TITLE
Search Criteria's(Feilds) Required.

### ISSUE THREAD

**Issue by DeshaniPubudu** [hmislk/hmis#6675]
1. Date Type (Dropdown)
- Ordered Date (Default)
- Sample Generated Date
- Sample Collected Date
- Sample Send Date
- Sample Accepted Date

2. Date Range (Form Date & To Date)
3. Ordering Location
4. Sample Id
5. Patient Name
6. Specimen (Dropdown)
7. Priority (Dropdown)

8. Status (Dropdown)
- Ordered
- Sample Generated (Barcode generated)
- Sample Collected
- Sample Send
- Sample Accepted
- Sample Rejected
- Sample Reverted
- Sample Resend
- Sample Recollected
- Sample Interfaced
- Sample Approved
- Sample Repeated
- Sample Approved and Repeated.

9. Referring Doctor
10. External Doctor (Point 2)
11. Equipment (Dropdown)
12. Laboratory (Categories)
13. Investigation

14. Type  (Dropdown)
- OP
- IP
- CC

15. By Route (CC Routes)  (Dropdown)
16. By Collection Center (Autocomplete) (Search by Name Or Code)

**Comment by Irani96** [comment]
fixed
