### ISSUE TITLE
All Sales Report - OPD 

### ISSUE THREAD

**Issue by DeshaniPubudu** [hmislk/hmis#7128]
(https://drive.google.com/file/d/1nAeSMBLqMZkbdMd_FF4Fb-YZOldhIrIN/view?usp=drive_link)

1. Bill No
2. Patient Name
3. Date
4. Hospital Fee
5. Doctor Fee/Technician Fee
6. Total
7. Cash
8. Card
9. Multiple Payment Method (Cash,Card)
10. Staff
11. Agent
12. Discount
13. Actual Total

- Need Calculating the total for each payment method
- Need Filter For each Payment Method
- Need to Select Date Range

**Comment by buddhika75** [comment]
can not give payment method
as one bill can contain multiple payments
