### ISSUE TITLE
All Sales Report - X Ray

### ISSUE THREAD

**Issue by DeshaniPubudu** [hmislk/hmis#7129]
https://drive.google.com/file/d/1BDTVKNDdkQwRkVHpUs-pzptyjRUzJZoc/view?usp=drive_link

1. Bill No
2. Patient Name
3. Date
4. Hospital Fee
5. Doctor Fee/Technician Fee
6. Total
7. Cash
8. Card
9. Multiple Payment Method
10. Staff
11. Agent
12. Discount
13. Actual Total

- Need Calculating the total for each payment method
- Need to Select Date Range

**Comment by buddhika75** [comment]
Closes with #7132 

Please check and close

**Comment by buddhika75** [comment]
Not closed. Will develop it

**Comment by buddhika75** [comment]
Can not add Payment Method hare, as one bill can be from different payment methods.

**Comment by buddhika75** [comment]
Menu > OPD > OPD Analytics > Lists > Sale Report 

Select Department as Radiology

And take the value
