### ISSUE TITLE
The agent code should be uploaded as a Integer and not as a Float

### ISSUE THREAD

**Issue by DeshaniPubudu** [hmislk/hmis#7227]
The agent code should be uploaded as a Integer and not as a Float

Administration/Manage Institution/Bulk Transaction/Upload Agencies
admin/institutions/agency_upload.xhtml

Administration/Manage Institution/Manage/Manage Institution/Code
admin/institutions/institution_management.xhtml

**Comment by buddhika75** [comment]
Add ' before the code, so that there will be no decimals
