### ISSUE TITLE
Shift End Bill List

### ISSUE THREAD

**Issue by buddhika75** [hmislk/hmis#7239]
Shift End Bill List

Base on the file Shift End Bill List initial_fund_bill_list
xhtml file in reports/cashier_reports
shift_stats_and_ends

Navigation

Menu > Reports > Reports > Cashier Reports > Shift starts and Ends

Filters
From	
Ex. 17 Sep 2024 00:00:00
To	
Ex. 17 Sep 2024 23:59:59
Institution	
Department	
All Departments
Site*	
User

Columns
No. User Shift Srat(date & Time) Shift End(date & Time) Short/Excesses

Links
Shift Start (view) > Separate Issue
Shift End(View) > Separate Issue

New Bill Type > Reimburse Shortage > Separate Issues

**Comment by DamithDeshan** [comment]
This Issue has bean Missing in this Location
Menu > Reports > Reports > Cashier Reports > Shift starts and Ends
