### ISSUE TITLE
Create a report for WHT

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#7425]
Create a report for WHT
(Report/Financial Report/WHT)

https://ruhunuhospitals-my.sharepoint.com/:x:/r/personal/admin_ruhunuhospital_lk/_layouts/15/Doc.aspx?sourcedoc=%7B88E36B91-AEFE-43E1-B835-76B4C3A0169E%7D&file=07.%20System%20generate%20reports%20(Dinesha)%20(Accounts).xlsx&action=default&mobileredirect=true

**Comment by buddhika75** [comment]
Export to excel was not there, I am adding them to all 3 reports.
