### ISSUE TITLE
Improvements in DAILY RETURN report

### ISSUE THREAD

**Issue by DeshaniPubudu** [hmislk/hmis#7837]
Daily Return Report Issue
1. Settle OPD Bill using the Multiple payment method, (cash+card) bill amount wasn't updated in OPD Services Collection.
   But Card amount was updated in Card Transaction Details.
2. Professional Payments for OPD Services add to the Net Cash Total.
3. Credit Company Collection for OPD Services not updated
4. Patient Deposit Collection wasn't updated
5. Date Range not working for Card Transaction Details & Collecting Centre Collection

**Comment by buddhika75** [comment]
Issues corrected
1. THose are filtered only by date, now filter to date and time
2, When more than one is given for quantities to items like dressings, they are counted under the qty in OPD collection
3. If a patient deposit is returned, it will appear as a minus, but that needs to be corrected at the time of returning. an issue was raised for that -
