### ISSUE TITLE
OPD bill refund should be debited, it should be reduced from the balance in patient ledger

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#7854]
OPD bill refund should be debited it should be reduced from the balance.
The status wasn't displayed
The total should be updated.(Credit/debit)
patient_deposit/patient_deposit_history.xhtml

**Comment by DARKDRAGON-LK** [comment]
No Issues Found.!

- OPD Bill Refund Should be Credited in to the Patient Deposit because it adds back to the Patient Deposit Total.
- OPD Bill Only Effect on Patient Deposit if the Refund Payment Method is  Patient Deposit. (when refund is cash is doesn't effect to patient deposit total)
