### ISSUE TITLE
Even if send without selecting the card in Shift Handover, Will receive with the card in Shift Handover to Accept

### ISSUE THREAD

**Issue by DeshaniPubudu** [hmislk/hmis#7962]
1. Even if send without selecting the card 
    My Shift/Handover

2. Will receive with the card
    Handover Management/Shift Handover to Accept

**Comment by buddhika75** [comment]
Done
Please check with Cards

I am NOT selecting card
![hanover - card NOT selected](https://github.com/user-attachments/assets/66a6b10d-72ff-45d9-a5fa-9050b609e7d7)

Card NOT printed in receipt.
![handover print - no card is displayed](https://github.com/user-attachments/assets/f8ecf91a-1fa2-4fb2-aef7-6a72b948bada)

Card NOT shown at handover accept
![handover accept - no card](https://github.com/user-attachments/assets/d73e7d54-5f2c-4922-83c3-108379442b68)
