### ISSUE TITLE
Bill Generated Date & Time was wrong in Deposit Bill for Collecting Center Bill

### ISSUE THREAD

**Issue by DeshaniPubudu** [hmislk/hmis#7996]
Reports/CC Report/CC Receipt/Bill No -----> View Bill-----> Deposit Bill for Collecting Center
collecting_centre/view/cc_payment_received_bill_view.xhtml

1. Bill Generated Date & Time was wrong

**Comment by DamithDeshan** [comment]
Already Fixed #7997
