### ISSUE TITLE
Patient Deposit Refunds need to Deduct from Total in Daily Return Report

### ISSUE THREAD

**Issue by DeshaniPubudu** [hmislk/hmis#8047]
Patient Deposit Refunds need to Deduct from Total. 
Currently  refund amount is Added to Patient Deposit Payments total.

![Image](https://github.com/user-attachments/assets/9b3ff586-0b35-4868-afcd-75b520e876c6)

**Comment by buddhika75** [comment]
Its done. Please check, I am closing it, If not, reopen

**Comment by DeshaniPubudu** [comment]
This issue was already fixed
