### ISSUE TITLE
001 (Fucidine Tulle)(219/A) This item added by Qty(2 Qty) but in the Daily return Show 1 Qty.

### ISSUE THREAD

**Issue by DeshaniPubudu** [hmislk/hmis#8048]
001 (Fucidine Tulle)(219/A) This item added by Qty(2 Qty) but in the Daily return Show 1 Qty.

**Comment by buddhika75** [comment]
It is already working.

I created one bill with 4 as qty for above item
![Image](https://github.com/user-attachments/assets/6e63c55c-9436-47b7-942e-4edb20e86d60)

Now it shows the qty in Daily Return


![Image](https://github.com/user-attachments/assets/6c251bc1-8e1c-4649-9db5-d0f4a2215f2b)
