### ISSUE TITLE
Cashier Details

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#8232]
OPD Credit  bill isn't updated
OPD PatientDeposit bill isn't updated under PatientDeposit

Agency Management
Other amount isn't updated and the net total was updated(Cheque/Slip)

Patient Deposit Management
Patient Deposits/Patient Deposit Refunds - Other amount isn't updated and the net total was updated(cheque, slip & ect.)
                                                                      E-wallet isn't updated

**Comment by DeshaniPubudu** [comment]
Not Fix
