### ISSUE TITLE
Need Validation for Handover Cash Difference

### ISSUE THREAD

**Issue by DeshaniPubudu** [hmislk/hmis#8339]
Need Validation for Handover Cash Difference

**Comment by buddhika75** [comment]
Done
Cash can be selected
Users can start the Hanover process only if the selected cash value and denominator total are less than one.

**Comment by buddhika75** [comment]
![handover 2](https://github.com/user-attachments/assets/5ada1590-1fec-4069-af59-c7875b27e1a9)

**Comment by Irani96** [comment]
When have Rs 1 different can handover validation isn't displayed
