### ISSUE TITLE
An icon is required in front of each staff name to redirect to the drawer dashboard.

### ISSUE THREAD

**Issue by DeshaniPubudu** [hmislk/hmis#8369]
- [x] An **icon** is required in front of each staff name to redirect to the **drawer dashboard**.
- [ ] The drawer dashboard should be redirected from **view only mode**

Report Path
Reports/Cashier Reports/All Drawer
reports/cashier_reports/all_drawers.xhtml

Drawer Dash Board Path
Manage User/View & Select User/ Manage Drawer
admin/users/drawer.xhtml

**Comment by IsuruUdaraRanaweera** [comment]
View Only Mode didn't added yet

**Comment by Irani96** [comment]
Added issue for unfix issue #8578
