### ISSUE TITLE
Credit bill isn't updated on daily return

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#8371]
Credit bill isn't updated on daily return
reports/financialReports/daily_return.xhtml

**Comment by buddhika75** [comment]
OPD Credit Bills are updated at the end of the daily return

Please note : Credit Bills are not taken into consideration at the top for OPD Service Collection

**Comment by buddhika75** [comment]
![screencapture-localhost-8080-rh-faces-reports-financialReports-daily-return-xhtml-2024-10-31-04_50_32](https://github.com/user-attachments/assets/66dca72b-abe8-4d1b-96bd-68f52be90252)
