### ISSUE TITLE
Summaries need to order by Default Date, Institution, Site, Department.

### ISSUE THREAD

**Issue by DeshaniPubudu** [hmislk/hmis#8566]
Summaries need to order by Default Date, Institution, Site, Department.

![Image](https://github.com/user-attachments/assets/2e1679f5-b643-4b30-8580-ef4710ace585)

Path:
Financial Transaction Manager/Handover Current Shift
cashier/handover_start_all.xhtml

**Comment by Irani96** [comment]
For refund it was't working(added issue #8585)
