### ISSUE TITLE
After clicking the add button, the previously added item was missing in the AMPs.

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#8616]
After clicking the add button, the previously added item was missing in the AMPs.
Path: Administration/Pharmaceutical Management/Medicine Component Management/Amps
Click the Add button and add Amp Details-> If click again Add button to add another medicine previously added medicine item was missing.
pharmacy/admin/amp.xhtml

**Comment by buddhika75** [comment]
As there are lot of AMPs, I have used an autocomplete. We do not list any AMP. Have to search from the autocomplete. Its the expected behaviour. I am closing the issues. If not, reopen.
