### ISSUE TITLE
Withholding Tax Report 

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#8623]
- [x]  After Process Report Report Type Filtre getting Reset every time.
- [x]  Speciality & Doctor Filtres not working.
- [x]  Visit Type Filtre Need to add CC 
- [x] In Pro Pay cancellation Need to reverse the WHT Amount also
![WhatsApp Image 2024-11-07 at 16 05 10_0d4e893d](https://github.com/user-attachments/assets/22b0a5fc-f085-4221-8046-7107ef6cbc69)

**Comment by buddhika75** [comment]
this is not necessary - Visit Type Filtre Need to add CC

Informed RH

I will clsoe it. If any issue, please reopen
