### ISSUE TITLE
Daily Return Improvements

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#8666]
- [x] E-wallet - The e-wallet bill has not been updated.
- [x] Credit - The credit bill has not been updated.
- [x] Patient Deposit -  The Patient Deposit bill has not been updated.
- [x] Date- The date isn't working (From Date/To Date)
- [x] Petty Cash - Petty cash isn't updated

![Screenshot (1643)](https://github.com/user-attachments/assets/5b33278a-4521-4436-844d-6925a1404a0f)
![Screenshot (1644)](https://github.com/user-attachments/assets/2b5cdf3f-df73-428c-b617-28f69b35def3)

reports/qb/report_qb_day_income_with_out_professional.xhtml

**Comment by buddhika75** [comment]
there is no tasks related to the QB report, SO I have changed the topic. Add qb report issues, if any as a seperate issue.
