### ISSUE TITLE
Cancellation & Return Details required in Cheque - Handover

### ISSUE THREAD

**Issue by DeshaniPubudu** [hmislk/hmis#8668]
Cancellation & Return Details required in Cheque - Handover

![Image](https://github.com/user-attachments/assets/996b1b96-167a-4555-bc12-02a9cd207e66)

**Comment by buddhika75** [comment]
Payment Details Capture Updated in CC Deposits and CC Deposit Cancellation

**Comment by DeshaniPubudu** [comment]
Bank wasn't displayed in Handover 

![Image](https://github.com/user-attachments/assets/29dabd78-3b2f-4184-861a-d77e604c49e6)

**Comment by DeshaniPubudu** [comment]
Half Fix
Open Issue - #9265
