### ISSUE TITLE
E Wallet Should be required in  Handover

### ISSUE THREAD

**Issue by DeshaniPubudu** [hmislk/hmis#8673]
E Wallet Should be required in  Handover

![Image](https://github.com/user-attachments/assets/daad83cf-cae0-41e2-ac0f-41a88db48d46)

**Comment by buddhika75** [comment]
done
![eWallet in Handover](https://github.com/user-attachments/assets/360d0c5f-223e-4391-b726-510f9df811d6)
[Handover eWallet Receipt.pdf](https://github.com/user-attachments/files/17940670/Handover.eWallet.Receipt.pdf)
