### ISSUE TITLE
Create wireframe for OPD and Inward Due

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#8693]
Create wireframe for OPD and Inward Due

https://ruhunuhospitals-my.sharepoint.com/:x:/g/personal/admin_ruhunuhospital_lk/EXn3Gs8Qq5JFiNlmLSF4y-sBLF7myUJuEgfJA93rxMqr0Q?e=ANy8by&nav=MTVfezAwMDAwMDAwLTAwMDEtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMH0

**Comment by IsuruUdaraRanaweera** [comment]
reports/financialReports/opd_and_inward_due_report.xhtml
