### ISSUE TITLE
Create wireframe for Package Report

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#8698]
Create wireframe for Package Report

https://ruhunuhospitals-my.sharepoint.com/:x:/g/personal/admin_ruhunuhospital_lk/EZBHz2H_ogtJu_6TaNkOKckBCDCkVrwPTv8wsDqyy98ejg?e=J3GIob&nav=MTVfezlFREJFNzZBLTQxNTEtNDJDMi05MUNDLTczMzRDNDdDMzNENH0

**Comment by Irani96** [comment]
Error page was displayed can't test

**Comment by IsuruUdaraRanaweera** [comment]
Created the navigation in the search controller again. First time somehow navigation I created in the search controller was missing after the merge.
