### ISSUE TITLE
After select the Specialty, Doctor list was displayed twice - WHT Report

### ISSUE THREAD

**Issue by DeshaniPubudu** [hmislk/hmis#8827]
After select the Specialty, Doctor list was displayed twice - WHT Report

Reports/17. WHT/Withholding Tax Report

![Image](https://github.com/user-attachments/assets/e4f4b9b2-314f-43a5-8661-5a92b71f9ec0)

**Comment by buddhika75** [comment]
Done. Reopen if there are any issues.
