### ISSUE TITLE
Without a room, services cannot be added for the OPD CARD patient

### ISSUE THREAD

**Issue by DeshaniPubudu** [hmislk/hmis#8832]
Without a room, services cannot be added for the OPD CARD patient

explain:
Select Investigation & Click 'Add' button validation was displayed as "Please Set Room or Bed For This Patient"

Inward/Service & Items/Add Service & Investigation

**Comment by Irani96** [comment]
Not fix
![Image](https://github.com/user-attachments/assets/96331df2-6344-446a-b251-a5c276b9e844)
