### ISSUE TITLE
The comment box was displayed on the reprint page, but some details of the Payment Voucher were missing.

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#8833]
The comment box was displayed on the reprint page, but some details of the Payment Voucher were missing.
dealerPayment/search_dealor_payment.xhtml
Supplier Payment Management/Settled Payments/List Pharmacy Payment to settle/Click bill num link
![Screenshot (1699)](https://github.com/user-attachments/assets/c855d9fd-9fcf-4ee3-8873-a63c2571ad33)

**Comment by Pubudu-Piyankara** [comment]
Done

**Comment by Irani96** [comment]
Half fix & added issue for rest #8942
