### ISSUE TITLE
Create wireframe for Stock Ledger report

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#8854]
Create wireframe for Stock Ledger report

https://ruhunuhospitals-my.sharepoint.com/:x:/g/personal/admin_ruhunuhospital_lk/EZBHz2H_ogtJu_6TaNkOKckBCDCkVrwPTv8wsDqyy98ejg?e=bpEfVC&nav=MTVfe0JFNDcxMTQzLUFCN0UtNDU1RC1CMEIyLTE0ODhBRTM4MkE5M30

**Comment by DeshaniPubudu** [comment]
Half Fix.
Branch should correct as Institution, Site, Department
