### ISSUE TITLE
Create wireframe for Closing Stock report

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#8856]
Create wireframe for Closing Stock report

https://ruhunuhospitals-my.sharepoint.com/:x:/g/personal/admin_ruhunuhospital_lk/ERUI553d0URKlpi2eSN3BqkBM4rjTe8OpQA-uAiYirmNOg?e=YuOdMf&nav=MTVfezAwMDAwMDAwLTAwMDEtMDAwMC0wMTAwLTAwMDAwMDAwMDAwMH0

**Comment by DeshaniPubudu** [comment]
Half Fix - #8939
