### ISSUE TITLE
Create wireframe for Batch wise Stock

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#8857]
https://ruhunuhospitals-my.sharepoint.com/:x:/g/personal/admin_ruhunuhospital_lk/ERUI553d0URKlpi2eSN3BqkBM4rjTe8OpQA-uAiYirmNOg?e=5uyV04&nav=MTVfezAwMDAwMDAwLTAwMDEtMDAwMC0wMTAwLTAwMDAwMDAwMDAwMH0

**Comment by SandithP2001** [comment]
It is also Closing Stock Report

**Comment by DeshaniPubudu** [comment]
This report same as Closing Stock Report.
