### ISSUE TITLE
Create wireframe for Good In Transit report

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#8863]
https://ruhunuhospitals-my.sharepoint.com/:x:/g/personal/admin_ruhunuhospital_lk/Ec_NnGMZ-BxGi6xs3ef1djYBRnno6ionUjpLqJ6tSDdbnA?e=aaTR1m&nav=MTVfezAwMDAwMDAwLTAwMDEtMDAwMC0wNDAwLTAwMDAwMDAwMDAwMH0

**Comment by DeshaniPubudu** [comment]
Half Fix.
Issue open #9114
