### ISSUE TITLE
Create wireframe for Slow/Fast/None Movement Report

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#8864]
https://ruhunuhospitals-my.sharepoint.com/:x:/g/personal/admin_ruhunuhospital_lk/EYHRNDjl_g5NiOlMfMwRudgBKkjwIVqM9mDeVFlcI3dbyQ?e=DCeeuO&nav=MTVfe0Q0QzdDQUI3LUMzRUMtNEUxNi1CQjhFLUI5ODhEQUQ0MDRCRX0

**Comment by DeshaniPubudu** [comment]
Half Fix.
Added Issues - #9113
