### ISSUE TITLE
Create wireframe for Expiry Item Report

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#8865]
https://ruhunuhospitals-my.sharepoint.com/:x:/g/personal/admin_ruhunuhospital_lk/EZBHz2H_ogtJu_6TaNkOKckBCDCkVrwPTv8wsDqyy98ejg?e=bpEfVC&nav=MTVfe0JFNDcxMTQzLUFCN0UtNDU1RC1CMEIyLTE0ODhBRTM4MkE5M30

**Comment by DeshaniPubudu** [comment]
Half fix & Added issue - #9119
