### ISSUE TITLE
Serarch Patient Using PHN or Phone Number for All Billing Sections

### ISSUE THREAD

**Issue by DamithDeshan** [hmislk/hmis#8874]
Serarch Patient Using PHN or Phone Number for All Billing Sections
- OPD Billing
- Billing for Cashier
- CC Billing
- Package Billing
- Patient Admit
- Phatmacy Billing (Sale and Sale for Cashier)

**Comment by DeshaniPubudu** [comment]
'No Patient Found' Validation Isn't displayed in OPD Billing & Package Billing - #8902
