### ISSUE TITLE
Improvements in Package Report 

### ISSUE THREAD

**Issue by DeshaniPubudu** [hmislk/hmis#9004]
- [x] Service Processed Date : 
For example, the Date on which investigation like FBS, ESR, FMR begin processing.

- [x] Admission Date :
Date the patient was admitted to the Inward

- [x] Discharge Date and Time : 
Date & Time of the Patient Discharge

- [x] Sponsor : 
Need Credit Company Name

- [x] Plan Name : 
If the credit company has a plan related to the package bill, it should be displayed.

- [x] Ref Dep : 
Need Reffering Dr Specialty

- [x] Ref Dr : 
Need Reffering Dr Name

- [x] Rendering Dept:
Need Performing Department

- [x] Rendering Dr :
Need Performing Dr Name

- [x] Invoice Status : 
Invoice process status (for example: Settled, Unsettled)

- [x] Charge Class : 
Service Department

- [x] Bed No : 
Need Patient's Bed No

reports/financialReports/package_report.xhtml
Reports/Financial Reports/Package Report

**Comment by ImeshRanawellaSG** [comment]
Package bills are not available for inward patients in the current system. Therefore, can't Bed no, admission date, discharge date will always be N/A
