### ISSUE TITLE
Collection Center Wise Invoice List Report

### ISSUE THREAD

**Issue by ImeshRanawellaSG** [hmislk/hmis#9033]
Collection Center Wise Invoice List

https://ruhunuhospitals-my.sharepoint.com/:x:/g/personal/admin_ruhunuhospital_lk/EdyaAZa9r3dFsxXHOTH0cDoB3O0VS4Fe9JL0yGaTW0Fpig?e=A2oceB&nav=MTVfezAwMDAwMDAwLTAwMDEtMDAwMC0wNjAwLTAwMDAwMDAwMDAwMH0

reports/collection Center Reports/collection center wise invoice list

**Comment by Irani96** [comment]
added issue  #9090
