### ISSUE TITLE
Payment Details with Package bill

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#9215]
- [x] Staff Credit- Staff  should displayed as Staff Credit (text)
- [x] Credit - Ref No, Memo is missing
- [x] Staff Welfare - Staff Welfare should displayed as Staff Welfare (text)
- [x] Discount is missing
- [x] Comment is missing

/opd/opd_bill_package.xhtml

**Comment by buddhika75** [comment]
Discounts are not given for Package

**Comment by buddhika75** [comment]
Please note discount is not calcualted in package billing. Please contact me if a customer want to discuss it further.
