### ISSUE TITLE
Icons aren't working on package bill

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#9217]
- [x] Manage Bill - Manage Bill isn't working
- [x] Manage Batch Bill - Manage Batch Bill isn't working
- [x] View Bill - View Bill isn't working
- [x] View Batch Bill - View Batch Bill isn't working

Do this on the package bill search

**Comment by buddhika75** [comment]
Please check OPD Package Batch Bill Cancellation Process and Individual Cancellation Process.

OPD Package Batch Bill Cancellation Completely Rewritten.
OPD Package Individual Bill Cancellation NOT checked or done.

**Comment by DeshaniPubudu** [comment]
Batch Bill Cancellation & Individual Cancellation working properly for Cash,Card,Credit. 
I checked (Shift End, Drawer, My Drawer History & Cashier Summaries)

But it not work properly for Multiple Payment & Patient Deposit
