### ISSUE TITLE
If refund package bill it was not as OPD bill payment data not displayed

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#9220]
If refund package bill it was not as OPD bill payment data not displayed

**Comment by buddhika75** [comment]
I added a package bill. Then I searched it and returned one item. I used cash for both transactions. The Payments were created as expected. I can not find any error. Please schedule a meeting if the error persists. Alternatively, you can link to a video.

![image](https://github.com/user-attachments/assets/7883eaeb-37a7-4df1-86b8-a64ca396d031)
