### ISSUE TITLE
After paid professional payment cannot be cancel the billed opd bill

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#9225]
After Done the Doct payment should restrict OPD bill Cancellation. If Need to cancel the OPD Bill Need to cancel Doctor's payment First. Then cancel the OPD Bill.
https://youtu.be/idNjERvELlI

**Comment by buddhika75** [comment]
Now Individual OPD Bills can NOT be cancelled if the professional payments are already made. First, have to cancel the professional fee payments before cancelling the OPD Bills.

**Comment by buddhika75** [comment]
![image](https://github.com/user-attachments/assets/82204247-355c-47f7-8cdc-7a1c27ef61e0)

**Comment by buddhika75** [comment]
![image](https://github.com/user-attachments/assets/2486dab9-eea4-475e-bbaa-9a9aa4ca8896)
