### ISSUE TITLE
OPD Credit Company Settle Bill Search

### ISSUE THREAD

**Issue by buddhika75** [hmislk/hmis#9229]
OPD Credit Company Settle Bill Search

**Comment by buddhika75** [comment]
Menu > Payments > Credit COmpany > OPD Credit Bill Settle 
![Credit Company Settle bill list](https://github.com/user-attachments/assets/f463575e-26cc-41af-b2fc-c06f6ab60fb4)
Search

**Comment by Irani96** [comment]
added issue #9289
