### ISSUE TITLE
Collecting center deposit cancellation isn't updated

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#9260]
- [x] Collecting center deposit cancellation isn't updated on the cashier **shift end summary**
- [x] Collecting center deposit cancellation isn't updated on the  **All cashier summary**
- [x] Collecting center deposit cancellation isn't updated on the  **Cashier Summary**
- [x] Collecting center deposit cancellation isn't updated on the  **Cashier Detail**

**Comment by DeshaniPubudu** [comment]
Added Issue - #9293
