### ISSUE TITLE
Admission Needed Header and Logo preference isn't working

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#9262]
Admission Needed Header and Logo preference isn't working(ADMISSION CASE SHEET)

**Comment by DARKDRAGON-LK** [comment]
Used Following Values to Test this : 

- Height For Logo on Admission Sheet  :  130
- Width For Logo on Admission Sheet  :  300
- URL For Logo on Admission Sheet : https://i.ibb.co/4VzkyLd/rhd-logo.png
