### ISSUE TITLE
Need Radio Button for Discharge/Added Date in Discount Wireframe

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#9286]
For the date range filtres, better to mannage with Radio Button Selection For this Report.

- [x] Added Date
- [x] Discharge Date.
- [x] User Need to Select Ithre Added Date Or Discharge Date. By Default Added Date Selected.

**Comment by IsuruUdaraRanaweera** [comment]
reports/financialReports/discount.xhtml
