### ISSUE TITLE
CC balance before transaction issue on CC statement report

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#9298]
ex: In RCC116 issues were the CC balance before the transaction wasn't updated & Added bill hos fee was reduced from the CC balance before a transaction, not CC balance after the transaction.(12 11 2024 11:45:33 AM)

In RCC165 After done CC deposit- The received cc amount was reduced from the CC balance before the transaction not the cc balance after the transaction(10 11 2024 02:41:15 PM)

In RCC209 same as RCC 116 (10 11 2024 02:44:57 PM)
CC balance isn't updated sometimes

**Comment by buddhika75** [comment]
Done, But in the production, need to adjust the balance.

![image](https://github.com/user-attachments/assets/bce18e4a-f828-43ca-84f5-4037edd6f3d4)
