### ISSUE TITLE
Need save button for BHT ISSUE REQUEST FOR 

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#9302]
ward/ward_pharmacy_bht_issue_request_bill.xhtml
Request medicine from Pharmacy View Save Button. Need to Save Current Document. Then need to edit the document(Add Drugs, Remove added Drugs, Edit added item Qtys). After Approved Or Finalized only show to issue Pharmacy side

**Comment by Irani96** [comment]
Not Fix

**Comment by Pubudu-Piyankara** [comment]
ward/ward_pharmacy_bht_issue_request_bill.xhtml
Request medicine from Pharmacy View Save Button. Need to Save Current Document. Then need to edit the document(Add Drugs, Remove added Drugs, Edit added item Qtys). After Approved Or Finalized only show to issue Pharmacy side.

I did not add a save button. there is edit option once after settled the bill. you can search requested list in inward >  pharmacy > view pharmacy request. In this page you can search bills one by one and if you need to edit medicines you can do it by cllicking > view request > edit request buttons.
