### ISSUE TITLE
Staff Welfare Report

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#9337]
- [x] Balance Amount - The patient's balance amount was not updated
                         Ex: If patient staff welfare started amount was 1000 if added 420 FBC  Balance Amount should be 580
                               If another day bills the same person for FBS 470, the Balance Amount should be 110 (In the last amount 
                               was updated for all)

![Screenshot (1760)](https://github.com/user-attachments/assets/64f4c7bb-a3ab-4c85-adc1-912c6054960a)

- [x] Bill No - RH mention on the format it's only for pharmacy
- [x] Invoice No- Invoice No is not updated.
- [x] If cancel the bill it wasn't updated (Balance Amount)
- [x] The return isn't updated. (refund)
- [x] Staff - The Staff filter isn't working
- [x] Need report name instead of BundleName (Staff Welfare report)
- [x] Excel & PDF isn't working

**Comment by ImeshRanawellaSG** [comment]
Can't calculate balance by each bill in the current system
