### ISSUE TITLE
BHT Issue Request View After opening the Requested Document Patent Details(BHT Details) Need to show.

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#9340]
BHT Issue Request View After opening the Requested Document Patent Details(BHT Details) Need to show.

**Comment by Pubudu-Piyankara** [comment]
![image](https://github.com/user-attachments/assets/421457f3-d9cb-4945-820e-a7f9b50e4145)
/ward/ward_pharmacy_bht_issue_request_list_for_issue.xhtml
