### ISSUE TITLE
Sample Carrier

### ISSUE THREAD

**Issue by ImeshRanawellaSG** [hmislk/hmis#9352]
Sample Carrier

https://ruhunuhospitals-my.sharepoint.com/:x:/g/personal/admin_ruhunuhospital_lk/EStNkzTaHI9Dm8eesZ1lgboB27XBrjbidSXmY3XZGP7-Cw?e=szd9oP&nav=MTVfezE0QzEyMTlDLTMzRTItNEFBRC1CNUU4LUI1N0E1RERBMDFCQn0

reports/laboratory reports/sample carrier

**Comment by Irani96** [comment]
Added issues #9419
