### ISSUE TITLE
Collction Centre Book Wise Detail

### ISSUE THREAD

**Issue by ImeshRanawellaSG** [hmislk/hmis#9358]
Collction Centre Book Wise Detail

https://ruhunuhospitals-my.sharepoint.com/:x:/g/personal/admin_ruhunuhospital_lk/EdyaAZa9r3dFsxXHOTH0cDoB3O0VS4Fe9JL0yGaTW0Fpig?e=XDBJrL&nav=MTVfe0M5NTE2M0Q3LUE1RjEtNDU1Ni05M0IyLUUxRjJDRTdCMkY4OX0

Report/Collection Center Report/Collction Centre Book Wise Detail

**Comment by Irani96** [comment]
added issue #9428
