### ISSUE TITLE
Need WHT improvment

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#9381]
- [x] If "WHT" is selected, it should be added to the doctor's payment.
- [x] If WHT is not selected, it will not be added to the doctor’s payment.

**Comment by buddhika75** [comment]
Relavant Configuration Options
![image](https://github.com/user-attachments/assets/ac7503cb-6cb9-4962-9d62-f29ef74f68c5)

**Comment by buddhika75** [comment]
![image](https://github.com/user-attachments/assets/25b08461-2a91-4158-b63c-531275d3b1cc)

**Comment by buddhika75** [comment]
Please note that this is done only for OPD Professional Payments. Create separate issues for all others.
