### ISSUE TITLE
Can be paid if patient deposit is 0

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#9386]
Can be paid if patient deposit is 0 -OPD Packages
(https://youtu.be/RmHwdFclgNM

**Comment by buddhika75** [comment]
Discussed with @DamithDeshan . He will not do this. I am taking over.

**Comment by buddhika75** [comment]
Completed.

**Comment by DeshaniPubudu** [comment]
Not Fix

**Comment by buddhika75** [comment]
Done.
![image](https://github.com/user-attachments/assets/5283b4b4-56af-4430-b503-4684151bcff1)
