### ISSUE TITLE
Patient Deposit Payment Method is not working properly in Package Billing

### ISSUE THREAD

**Issue by DeshaniPubudu** [hmislk/hmis#9399]
- [x] Select the Patient Deposit Payment Method, displayed as 'Patient has NO Patient Deposit' in Payment Details.
explain:
Patient Has Patient Deposit & Can settle the package Bill. 

- [x] After a package bill is settled with a patient deposit, the amount is not deducted from the patient's deposit amount.
explain:
The patient has a deposit of 5000
Even after settling a package bill of 4000, the payment deposit is still shown as 5000

OPD/Billing/Package Billing
opd/opd_bill_package.xhtml

**Comment by buddhika75** [comment]
Have to set the Option  to automatically set the Payment method

![image](https://github.com/user-attachments/assets/56a1faf0-a3a3-4877-a17c-35941bf4e392)

**Comment by buddhika75** [comment]
Have to have Patient Deposit Method Enabled

![image](https://github.com/user-attachments/assets/27160eaf-4758-439a-af33-b42f20e4ab9b)
