### ISSUE TITLE
Sample Carrier

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#9419]
- [x] Staff - The updated staff name was wrong 
- [x] BHT No -BHT No should only updated for inpatient
- [x] Duration (Minutes) - Isn't updated
- [x] Sample ID - Sample ID was missing.
- [x] The current date-entered data isn't updated on the report.

reports/lab/sample_carrier.xhtml

**Comment by ImeshRanawellaSG** [comment]
fixed for new bills
