### ISSUE TITLE
Inconsistency in Patient Data Update After OPD Billing

### ISSUE THREAD

**Issue by buddhika75** [hmislk/hmis#944]
**Description:**
When using our Health Information Management System (HIMS), we have identified an issue related to updating patient data after billing in the Outpatient Department (OPD). This issue affects the synchronization of changes made during OPD billing with the patient's overall record.

**Steps to Reproduce:**
1. Search for a patient within the system.
2. Select the patient and proceed to the OPD billing section.
3. Modify patient data, such as name or date of birth, during the OPD billing process.
4. Add relevant services to the OPD bill.
5. Complete the OPD billing by settling the bill.
6. Search for the same patient again.

**Expected Behavior:**
The changes made to the patient's data during the OPD billing process should be accurately reflected in the patient's overall record when searching for them again.

**Current Behavior:**
Unfortunately, the changes made in the OPD bill page are not updated in the patient's record when searching for them again. This creates a discrepancy in the patient's information, which can lead to data inconsistency and potential errors in patient care.

**Additional Information:**
- This issue has been observed consistently and needs immediate attention to maintain data integrity within the system.
- The problem might be related to the data synchronization process between the OPD billing module and the patient's central record.

**Proposed Solution:**
We need to investigate the root cause of this synchronization issue and implement a fix to ensure that changes made during OPD billing are promptly reflected in the patient's overall record.

**Comment by DeshaniPubudu** [comment]
Done
