### ISSUE TITLE
External Laboratory Work Load

### ISSUE THREAD

**Issue by ImeshRanawellaSG** [hmislk/hmis#9481]
External Laboratory Work Load

https://ruhunuhospitals-my.sharepoint.com/:x:/g/personal/admin_ruhunuhospital_lk/EStNkzTaHI9Dm8eesZ1lgboB27XBrjbidSXmY3XZGP7-Cw?e=szd9oP&nav=MTVfezE0QzEyMTlDLTMzRTItNEFBRC1CNUU4LUI1N0E1RERBMDFCQn0

reports/laboratory reports/external laboratory workload

**Comment by Irani96** [comment]
added issue #9550
