### ISSUE TITLE
Create Pharmacy Income Report

### ISSUE THREAD

**Issue by DeshaniPubudu** [hmislk/hmis#9571]
Create Pharmacy Income Report

![Image](https://github.com/user-attachments/assets/ee6b9311-8aea-446a-a4e3-77b9ea14e57e)

**Comment by buddhika75** [comment]
Done with Limitations

Tasks to do

- [ ] Bill Type Atomic for Inpatient Direct Medicine Issue
- [ ] Bill Type Atomic for Inpatient Issues for Requests
- [ ] Bill Type Atomic for Theatre Direct Issue
- [ ] Bill Type Atomic for Theatre Issues for Requests
- [ ] Bill Type Atomic for Cancellation of Inpatient Direct Medicine Issue
- [ ] Bill Type Atomic for Cancellation of  Inpatient Issues for Requests
- [ ] Bill Type Atomic for Cancellation of  Theatre Direct Issue
- [ ] Bill Type Atomic for Cancellation of  Theatre Issues for Requests
- [ ] Bill Type Atomic for Return of Inpatient Direct Medicine Issue
- [ ] Bill Type Atomic for Return of  Inpatient Issues for Requests
- [ ] Bill Type Atomic for Return of  Theatre Direct Issue
- [ ] Bill Type Atomic for Return of  Theatre Issues for Requests
- [ ] Update the Pharmacy Income Report with New Bill Type Atomics
- [ ] Add Service Charge to Bill Entity
- [ ]  for Inpatient Direct Medicine Issue
- [ ] Bill Type Atomic for Inpatient Issues for Requests
- [ ] Bill Type Atomic for Theatre Direct Issue
- [ ] Bill Type Atomic for Theatre Issues for Requests

**Comment by buddhika75** [comment]
![image](https://github.com/user-attachments/assets/5096eb56-4d3d-4090-8d4f-4f50231cee31)

**Comment by DeshaniPubudu** [comment]
Half Fix
