### ISSUE TITLE
OPD Weekly Report

### ISSUE THREAD

**Issue by ImeshRanawellaSG** [hmislk/hmis#9580]
OPD Weekly Report

https://ruhunuhospitals-my.sharepoint.com/:x:/g/personal/admin_ruhunuhospital_lk/EcPt7ErOGUdIoP_fk82hiQUBRJRuD1SJEBa84aXpv5pvJQ?e=GTUHPx

reports/managementReports/opd_weekly

Contains only summary bill. Need to implemenet detail bill later

**Comment by Irani96** [comment]
page isn't loaded

**Comment by ImeshRanawellaSG** [comment]
Works fine now
