### ISSUE TITLE
CC Statement Payment Need to Identify in Different Colour

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#9778]
CC Statement Payment Need to Identify in Different Colour

**Comment by DamithDeshan** [comment]
### **User this Options**

1. Collecting Centre Payment Received Bill Row Color in CC Statement       --------->       ( default Color - #79f199 )
2. Collecting Centre Payment Cancel Bill Row Color in CC Statement       --------->       ( default Color - #df8663)
