### ISSUE TITLE
Improvements in Consumption Report

### ISSUE THREAD

**Issue by DeshaniPubudu** [hmislk/hmis#9783]
**Report Type** = **Department Unit Issue By Bill Item**
- [x] Request No - Not Updated
- [x] Created Date & Time - The data that should be displayed here is displayed in the 'Approved Date and Time' column.
- [x] Document Created By - The data that should be displayed here is displayed in the 'Document Approved By' column.

- [x] After the Issue Return - Total Value was wrong.
![20 12 2024 ss3](https://github.com/user-attachments/assets/bdc33352-0298-4ffc-9ae2-ccaff8b88026)

**Report Type** = **Category wise Issue Details By Department**
- [x] Not working

**Comment by Irani96** [comment]
half fix
