### ISSUE TITLE
Improvements in Stock Ledger Report

### ISSUE THREAD

**Issue by DeshaniPubudu** [hmislk/hmis#9785]
- [ ] Need a link to view bill
Doc No
Ref Doc No

- [x] Document Type = All Document Types
GRN Return Transaction Type should be "Stock Out"

- [x] Document Type = Transfer Issue 
Unnecessary details are also displayed in Transer Issue
Only Displayed Disbursement > Issue

- [x] Document Type = Transfer Receive 
Unnecessary details are also displayed in Transer Receive
Only Displayed Disbursement > Receive

- [x] Document Type = GRN
GRN Return bills are Not updated

- [x] Document Type = OP Sale
Pharmacy Retail sale not updated here

- [x] Document Type = IP Sale
Pharmacy Inpatient Medication Management issued drugs not updated here

- [x] Document Type = Consumption
Pharmacy disposals not updated here

**Comment by Irani96** [comment]
half fix
