### ISSUE TITLE
Upload Members

### ISSUE THREAD

**Issue by buddhika75** [hmislk/hmis#9842]
Upload Members

**Comment by buddhika75** [comment]
Menu > Admin > Manage Data, WOrkflows anf Forms > Data Upload > Upload Members

**Comment by buddhika75** [comment]
![image](https://github.com/user-attachments/assets/268c2a3f-c7f9-4f2f-b320-ea2bcf076616)

**Comment by DeshaniPubudu** [comment]
Phone No, NIC, Address is optional in this system.
But **Phone numbers** are required. Leaving only empty space and not allowing you to move forward
NIC - Can move forward with empty space
Address - Can move forward with empty space
