### ISSUE TITLE
Improvements in Search Family Membership

### ISSUE THREAD

**Issue by DeshaniPubudu** [hmislk/hmis#9857]
- [x] Need ****Pharmacy icon** for **Action**
- [x] Click the **Pharmacy icon** in the Action, should be redirected to the **pharmacy retail sale**.
- [x] Need Member Name Column
- [x] Also need to search for membership using the member's name

Membership/Search Family Membership
membership/family_membership_search.xhtml

**Comment by buddhika75** [comment]
![image](https://github.com/user-attachments/assets/9df34c40-4fe2-4fa6-ad91-c0d2677c9b31)

**Comment by buddhika75** [comment]
![image](https://github.com/user-attachments/assets/16963e11-a2c9-4df3-827e-c6292f3c5480)

**Comment by buddhika75** [comment]
![image](https://github.com/user-attachments/assets/90038ddc-2ae8-40ef-8945-1154e812b279)
